export const ADD_INCOME_ITEM = "ADD_INCOME_ITEM";
export const ADD_EXPENSE_ITEM = "ADD_EXPENSE_ITEM";
export const DELETE_INCOME_ITEM = "DELETE_INCOME_ITEM";
export const DELETE_EXPENSE_ITEM = "DELETE_EXPESE_ITEM";
