export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ADD_INCOME_ITEM = "ADD_INCOME_ITEM";
export const ADD_EXPENSE_ITEM = "ADD_EXPENSE_ITEM";
export const DELETE_INCOME_ITEM = "DELETE_INCOME_ITEM";
export const DELETE_EXPENSE_ITEM = "DELETE_EXPESE_ITEM";
export const CHECK_LOCAL_STORAGE = "CHECK_LOCAL_STORAGE";
export const SET_INITIAL_BUDGET = "SET_INITIAL_BUDGET";
